import React from 'react';

const Help = () => {
    return ( 
    <div className="help">
        <h1 class="help__question">1. Payment</h1>
        <p className="help__answer">Once you have entered your details online through our secure server, you have the option to store the card for use in the future, subsequent orders can be placed simply by logging into your account using your email address and password and selecting a credit card option from the list of those previously used - you would still have to enter the card's CVV number at this point.

We accept payments in Argentine Peso, Australian Dollar, Brazilian Real, Bulgarian Lev, Canadian Dollar, Chilean Peso, Colombian Peso, Czech Koruna, Danish Krone, Euro, Hong Kong Dollar, Hungarian Forint, Indian Rupee, Indonesian Rupiah, Israeli Shekel, Japanese Yen, Malaysian Ringgit, Mexican Peso, New Taiwan Dollar, New Zealand Dollar, Norwegian Krona, Peruvian Nuevo Sol, Philippine Peso, Polish Zloty, Pound Sterling, Qatari Rial, Romanian Leu, Saudi Arabian Riyal, Singapore Dollar, South African Rand, South Korean Won, Swedish Krona, Swiss Franc, Thai Baht, Turkish Lira, United Arab Emirates Dirham, Uruguay Peso, and US Dollar - there is a select currency dropdown menu at the top right of the homepage to change the currency display into the one most appropriate for you. We charge in the currency selected.</p>
        <h1 class="help__question">2. Payment</h1>
        <p className="help__answer">Once you have entered your details online through our secure server, you have the option to store the card for use in the future, subsequent orders can be placed simply by logging into your account using your email address and password and selecting a credit card option from the list of those previously used - you would still have to enter the card's CVV number at this point.

We accept payments in Argentine Peso, Australian Dollar, Brazilian Real, Bulgarian Lev, Canadian Dollar, Chilean Peso, Colombian Peso, Czech Koruna, Danish Krone, Euro, Hong Kong Dollar, Hungarian Forint, Indian Rupee, Indonesian Rupiah, Israeli Shekel, Japanese Yen, Malaysian Ringgit, Mexican Peso, New Taiwan Dollar, New Zealand Dollar, Norwegian Krona, Peruvian Nuevo Sol, Philippine Peso, Polish Zloty, Pound Sterling, Qatari Rial, Romanian Leu, Saudi Arabian Riyal, Singapore Dollar, South African Rand, South Korean Won, Swedish Krona, Swiss Franc, Thai Baht, Turkish Lira, United Arab Emirates Dirham, Uruguay Peso, and US Dollar - there is a select currency dropdown menu at the top right of the homepage to change the currency display into the one most appropriate for you. We charge in the currency selected.</p>
        <h1 class="help__question">3. Payment</h1>
        <p className="help__answer">Once you have entered your details online through our secure server, you have the option to store the card for use in the future, subsequent orders can be placed simply by logging into your account using your email address and password and selecting a credit card option from the list of those previously used - you would still have to enter the card's CVV number at this point.

We accept payments in Argentine Peso, Australian Dollar, Brazilian Real, Bulgarian Lev, Canadian Dollar, Chilean Peso, Colombian Peso, Czech Koruna, Danish Krone, Euro, Hong Kong Dollar, Hungarian Forint, Indian Rupee, Indonesian Rupiah, Israeli Shekel, Japanese Yen, Malaysian Ringgit, Mexican Peso, New Taiwan Dollar, New Zealand Dollar, Norwegian Krona, Peruvian Nuevo Sol, Philippine Peso, Polish Zloty, Pound Sterling, Qatari Rial, Romanian Leu, Saudi Arabian Riyal, Singapore Dollar, South African Rand, South Korean Won, Swedish Krona, Swiss Franc, Thai Baht, Turkish Lira, United Arab Emirates Dirham, Uruguay Peso, and US Dollar - there is a select currency dropdown menu at the top right of the homepage to change the currency display into the one most appropriate for you. We charge in the currency selected.</p>
        <h1 class="help__question">4. Payment</h1>
        <p className="help__answer">Once you have entered your details online through our secure server, you have the option to store the card for use in the future, subsequent orders can be placed simply by logging into your account using your email address and password and selecting a credit card option from the list of those previously used - you would still have to enter the card's CVV number at this point.

We accept payments in Argentine Peso, Australian Dollar, Brazilian Real, Bulgarian Lev, Canadian Dollar, Chilean Peso, Colombian Peso, Czech Koruna, Danish Krone, Euro, Hong Kong Dollar, Hungarian Forint, Indian Rupee, Indonesian Rupiah, Israeli Shekel, Japanese Yen, Malaysian Ringgit, Mexican Peso, New Taiwan Dollar, New Zealand Dollar, Norwegian Krona, Peruvian Nuevo Sol, Philippine Peso, Polish Zloty, Pound Sterling, Qatari Rial, Romanian Leu, Saudi Arabian Riyal, Singapore Dollar, South African Rand, South Korean Won, Swedish Krona, Swiss Franc, Thai Baht, Turkish Lira, United Arab Emirates Dirham, Uruguay Peso, and US Dollar - there is a select currency dropdown menu at the top right of the homepage to change the currency display into the one most appropriate for you. We charge in the currency selected.</p>
        <h1 class="help__question">5. Payment</h1>
        <p className="help__answer">Once you have entered your details online through our secure server, you have the option to store the card for use in the future, subsequent orders can be placed simply by logging into your account using your email address and password and selecting a credit card option from the list of those previously used - you would still have to enter the card's CVV number at this point.

We accept payments in Argentine Peso, Australian Dollar, Brazilian Real, Bulgarian Lev, Canadian Dollar, Chilean Peso, Colombian Peso, Czech Koruna, Danish Krone, Euro, Hong Kong Dollar, Hungarian Forint, Indian Rupee, Indonesian Rupiah, Israeli Shekel, Japanese Yen, Malaysian Ringgit, Mexican Peso, New Taiwan Dollar, New Zealand Dollar, Norwegian Krona, Peruvian Nuevo Sol, Philippine Peso, Polish Zloty, Pound Sterling, Qatari Rial, Romanian Leu, Saudi Arabian Riyal, Singapore Dollar, South African Rand, South Korean Won, Swedish Krona, Swiss Franc, Thai Baht, Turkish Lira, United Arab Emirates Dirham, Uruguay Peso, and US Dollar - there is a select currency dropdown menu at the top right of the homepage to change the currency display into the one most appropriate for you. We charge in the currency selected.</p>
        <h1 class="help__question">6. Payment</h1>
        <p className="help__answer">Once you have entered your details online through our secure server, you have the option to store the card for use in the future, subsequent orders can be placed simply by logging into your account using your email address and password and selecting a credit card option from the list of those previously used - you would still have to enter the card's CVV number at this point.

We accept payments in Argentine Peso, Australian Dollar, Brazilian Real, Bulgarian Lev, Canadian Dollar, Chilean Peso, Colombian Peso, Czech Koruna, Danish Krone, Euro, Hong Kong Dollar, Hungarian Forint, Indian Rupee, Indonesian Rupiah, Israeli Shekel, Japanese Yen, Malaysian Ringgit, Mexican Peso, New Taiwan Dollar, New Zealand Dollar, Norwegian Krona, Peruvian Nuevo Sol, Philippine Peso, Polish Zloty, Pound Sterling, Qatari Rial, Romanian Leu, Saudi Arabian Riyal, Singapore Dollar, South African Rand, South Korean Won, Swedish Krona, Swiss Franc, Thai Baht, Turkish Lira, United Arab Emirates Dirham, Uruguay Peso, and US Dollar - there is a select currency dropdown menu at the top right of the homepage to change the currency display into the one most appropriate for you. We charge in the currency selected.</p>
        <h1 class="help__question">7. Payment</h1>
        <p className="help__answer">Once you have entered your details online through our secure server, you have the option to store the card for use in the future, subsequent orders can be placed simply by logging into your account using your email address and password and selecting a credit card option from the list of those previously used - you would still have to enter the card's CVV number at this point.

We accept payments in Argentine Peso, Australian Dollar, Brazilian Real, Bulgarian Lev, Canadian Dollar, Chilean Peso, Colombian Peso, Czech Koruna, Danish Krone, Euro, Hong Kong Dollar, Hungarian Forint, Indian Rupee, Indonesian Rupiah, Israeli Shekel, Japanese Yen, Malaysian Ringgit, Mexican Peso, New Taiwan Dollar, New Zealand Dollar, Norwegian Krona, Peruvian Nuevo Sol, Philippine Peso, Polish Zloty, Pound Sterling, Qatari Rial, Romanian Leu, Saudi Arabian Riyal, Singapore Dollar, South African Rand, South Korean Won, Swedish Krona, Swiss Franc, Thai Baht, Turkish Lira, United Arab Emirates Dirham, Uruguay Peso, and US Dollar - there is a select currency dropdown menu at the top right of the homepage to change the currency display into the one most appropriate for you. We charge in the currency selected.</p>
        <h1 class="help__question">8. Payment</h1>
        <p className="help__answer">Once you have entered your details online through our secure server, you have the option to store the card for use in the future, subsequent orders can be placed simply by logging into your account using your email address and password and selecting a credit card option from the list of those previously used - you would still have to enter the card's CVV number at this point.

We accept payments in Argentine Peso, Australian Dollar, Brazilian Real, Bulgarian Lev, Canadian Dollar, Chilean Peso, Colombian Peso, Czech Koruna, Danish Krone, Euro, Hong Kong Dollar, Hungarian Forint, Indian Rupee, Indonesian Rupiah, Israeli Shekel, Japanese Yen, Malaysian Ringgit, Mexican Peso, New Taiwan Dollar, New Zealand Dollar, Norwegian Krona, Peruvian Nuevo Sol, Philippine Peso, Polish Zloty, Pound Sterling, Qatari Rial, Romanian Leu, Saudi Arabian Riyal, Singapore Dollar, South African Rand, South Korean Won, Swedish Krona, Swiss Franc, Thai Baht, Turkish Lira, United Arab Emirates Dirham, Uruguay Peso, and US Dollar - there is a select currency dropdown menu at the top right of the homepage to change the currency display into the one most appropriate for you. We charge in the currency selected.</p>
        <h1 class="help__question">9. Payment</h1>
        <p className="help__answer">Once you have entered your details online through our secure server, you have the option to store the card for use in the future, subsequent orders can be placed simply by logging into your account using your email address and password and selecting a credit card option from the list of those previously used - you would still have to enter the card's CVV number at this point.

We accept payments in Argentine Peso, Australian Dollar, Brazilian Real, Bulgarian Lev, Canadian Dollar, Chilean Peso, Colombian Peso, Czech Koruna, Danish Krone, Euro, Hong Kong Dollar, Hungarian Forint, Indian Rupee, Indonesian Rupiah, Israeli Shekel, Japanese Yen, Malaysian Ringgit, Mexican Peso, New Taiwan Dollar, New Zealand Dollar, Norwegian Krona, Peruvian Nuevo Sol, Philippine Peso, Polish Zloty, Pound Sterling, Qatari Rial, Romanian Leu, Saudi Arabian Riyal, Singapore Dollar, South African Rand, South Korean Won, Swedish Krona, Swiss Franc, Thai Baht, Turkish Lira, United Arab Emirates Dirham, Uruguay Peso, and US Dollar - there is a select currency dropdown menu at the top right of the homepage to change the currency display into the one most appropriate for you. We charge in the currency selected.</p>
        <h1 class="help__question">10. Payment</h1>
        <p className="help__answer">Once you have entered your details online through our secure server, you have the option to store the card for use in the future, subsequent orders can be placed simply by logging into your account using your email address and password and selecting a credit card option from the list of those previously used - you would still have to enter the card's CVV number at this point.

We accept payments in Argentine Peso, Australian Dollar, Brazilian Real, Bulgarian Lev, Canadian Dollar, Chilean Peso, Colombian Peso, Czech Koruna, Danish Krone, Euro, Hong Kong Dollar, Hungarian Forint, Indian Rupee, Indonesian Rupiah, Israeli Shekel, Japanese Yen, Malaysian Ringgit, Mexican Peso, New Taiwan Dollar, New Zealand Dollar, Norwegian Krona, Peruvian Nuevo Sol, Philippine Peso, Polish Zloty, Pound Sterling, Qatari Rial, Romanian Leu, Saudi Arabian Riyal, Singapore Dollar, South African Rand, South Korean Won, Swedish Krona, Swiss Franc, Thai Baht, Turkish Lira, United Arab Emirates Dirham, Uruguay Peso, and US Dollar - there is a select currency dropdown menu at the top right of the homepage to change the currency display into the one most appropriate for you. We charge in the currency selected.</p>
        
    </div> 
    );
}
 
export default Help;